name: nanoid_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  lints: ^6.0.0
  nanoid: ^1.0.0
  test: ^1.25.6
